import DeviceInfo from 'react-native-device-info'

export default [
  { label: 'Total Memory', value: DeviceInfo.getTotalMemory() },
  { label: 'Max Memory', value: DeviceInfo.getMaxMemory() },
  { label: 'API Level', value: DeviceInfo.getAPILevel() },
  { label: 'Application Name', value: DeviceInfo.getApplicationName() },
  { label: 'Brand', value: DeviceInfo.getBrand() },
  { label: 'Build Number', value: DeviceInfo.getBuildNumber() },
  { label: 'Bundle Id', value: DeviceInfo.getBundleId() },
  { label: 'Carrier', value: DeviceInfo.getCarrier() },
  { label: 'Device Country', value: DeviceInfo.getDeviceCountry() },
  { label: 'Device Id', value: DeviceInfo.getDeviceId() },
  { label: 'Device Locale', value: DeviceInfo.getDeviceLocale() },
  { label: 'Device Name', value: DeviceInfo.getDeviceName() },
  {
    label: 'First Install Time',
    value: new Date(DeviceInfo.getFirstInstallTime()).toLocaleDateString(),
  },
  { label: 'Font Scale', value: DeviceInfo.getFontScale() },
  { label: 'Free Disk Storage', value: DeviceInfo.getFreeDiskStorage() },
  { label: 'InstanceID', value: DeviceInfo.getInstanceID() },
  {
    label: 'LastUpdateTime',
    value: new Date(DeviceInfo.getLastUpdateTime()).toLocaleDateString(),
  },
  { label: 'Manufacturer', value: DeviceInfo.getManufacturer() },
  { label: 'Model', value: DeviceInfo.getModel() },
  { label: 'Phone Number', value: DeviceInfo.getPhoneNumber() },
  { label: 'Readable Version', value: DeviceInfo.getReadableVersion() },
  { label: 'Serial Number', value: DeviceInfo.getSerialNumber() },
  { label: 'System Name', value: DeviceInfo.getSystemName() },
  { label: 'System Version', value: DeviceInfo.getSystemVersion() },
  { label: 'Timezone', value: DeviceInfo.getTimezone() },
  { label: 'Total Disk Capacity', value: DeviceInfo.getTotalDiskCapacity() },
  { label: 'Unique ID', value: DeviceInfo.getUniqueID() },
  { label: 'User Agent', value: DeviceInfo.getUserAgent() },
  { label: 'Version', value: DeviceInfo.getVersion() },
  { label: 'Device Type', value: DeviceInfo.getDeviceType() },
]
